/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import useMouseCoordinates from '../../hooks/mouseCoordinates';
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
    const { x, y } = useMouseCoordinates();
    const group = useRef()
    const { nodes, materials } = useGLTF(`${process.env.PUBLIC_URL}/home.glb`)
    useFrame(() => {
        group.current.rotation.y = -1.4 + x * 0.5;
        group.current.rotation.x = y * 0.2;
    })

  return (
    <group ref={group} {...props} rotation={[0, -1.4, 0]} position={[0, -5, -10]} dispose={null}>
      <group position={[1.5, 1.31, 3.44]} rotation={[0, 0.13, 0]} scale={[0.1, 1.32, 0.66]}>
        <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
        <mesh geometry={nodes.Cube002_1.geometry} material={nodes.Cube002_1.material} />
      </group>
      <group position={[2.97, 4.74, -4.84]} rotation={[0, 0.68, 1.93]} scale={[0.18, 1.41, 0.18]}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials.pencil_ext_black} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.pencil_ext_yellow} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.pencil_wood} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={nodes.Cylinder_3.material} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials.pencil_eraser} />
        <mesh geometry={nodes.Cylinder_5.geometry} material={materials.pencil_metal} />
      </group>
      <group position={[0, 4.57, 0]} rotation={[0, -0.06, 0]} scale={[-0.23, 2.79, 4.7]}>
        <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} />
        <mesh geometry={nodes.Cube003_1.geometry} material={nodes.Cube003_1.material} />
      </group>
      <group position={[1.08, 2.15, 5.05]} rotation={[0, 0.13, 0]} scale={[0.11, 2.15, 1.31]}>
        <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} />
        <mesh geometry={nodes.Cube004_1.geometry} material={nodes.Cube004_1.material} />
      </group>
      <mesh geometry={nodes.Primitives.geometry} material={nodes.Primitives.material} position={[0.8, -0.4, 0.4]} />
    </group>
  )
}

useGLTF.preload(`${process.env.PUBLIC_URL}/home.glb`)
