/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/home.glb')
  return (
    <group ref={group} {...props} rotation={[0, -1.4, 0]} position={[0, -5, -10]} dispose={null}>
      <group position={[3.75, 1.31, 3.44]}>
        <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
        <mesh geometry={nodes.Cube002_1.geometry} material={nodes.Cube002_1.material} />
      </group>
      <group position={[4.24, 4.32, -1.9]}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials.pencil_ext_black} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.pencil_ext_yellow} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.pencil_wood} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials.pencil_graphite} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials.pencil_eraser} />
        <mesh geometry={nodes.Cylinder_5.geometry} material={materials.pencil_metal} />
      </group>
      <group position={[0, 4.57, 0]}>
        <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} />
        <mesh geometry={nodes.Cube003_1.geometry} material={nodes.Cube003_1.material} />
      </group>
      <group position={[2.59, 2.35, 5.05]}>
        <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} />
        <mesh geometry={nodes.Cube004_1.geometry} material={nodes.Cube004_1.material} />
      </group>
      <mesh
        geometry={nodes.computer_wireframe.geometry}
        material={nodes.computer_wireframe.material}
        position={[1.39, 0.31, 0.22]}
      />
      <mesh
        geometry={nodes.tablet_wireframe.geometry}
        material={nodes.tablet_wireframe.material}
        position={[0, 0.34, 0]}
      />
      <mesh geometry={nodes.phone_wireframe.geometry} material={nodes.phone_wireframe.material} />
    </group>
  )
}

useGLTF.preload('/home.glb')
