/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/room.glb --types
*/
/* eslint react/no-unknown-property: 0 */

import React, { type ReactElement } from 'react'

import { useGLTF } from '@react-three/drei'
import type * as THREE from 'three'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    walls: THREE.Mesh
    floor: THREE.Mesh
    flooring: THREE.Mesh
    desk: THREE.Mesh
    desk_leg: THREE.Mesh
    desk_shelfs_1: THREE.Mesh
    desk_shelfs_2: THREE.Mesh
    shelf_1: THREE.Mesh
    chair: THREE.Mesh
    chair_leg: THREE.Mesh
    chair_pillow: THREE.Mesh
    chair_support: THREE.Mesh
    chair_wheel: THREE.Mesh
    chair_wheel_protector: THREE.Mesh
    bookshelf: THREE.Mesh
    window: THREE.Mesh
    window_glass: THREE.Mesh
    window_glass_trim: THREE.Mesh
    curtain: THREE.Mesh
    curtain_1: THREE.Mesh
    curtain_2: THREE.Mesh
    curtain_holder_1: THREE.Mesh
    curtain_holder_2: THREE.Mesh
    computer_1: THREE.Mesh
    computer_2: THREE.Mesh
    computer_3: THREE.Mesh
    keyboard: THREE.Mesh
    mouse: THREE.Mesh
    mouse_scroll: THREE.Mesh
    notebook: THREE.Mesh
    notebook_hinge: THREE.Mesh
    notebook_keyboard: THREE.Mesh
    notebook_screen_1: THREE.Mesh
    notebook_screen_2: THREE.Mesh
    notebook_trackpad: THREE.Mesh
    mate_1: THREE.Mesh
    mate_2: THREE.Mesh
    straw: THREE.Mesh
    thermos: THREE.Mesh
    coaster: THREE.Mesh
    rug: THREE.Mesh
    book_1: THREE.Mesh
    book_2: THREE.Mesh
    book_1_2: THREE.Mesh
    book_1_3: THREE.Mesh
    book_2_2: THREE.Mesh
    book_2_3: THREE.Mesh
    book_3_1: THREE.Mesh
    book_3_2: THREE.Mesh
    book_4_1: THREE.Mesh
    book_4_2: THREE.Mesh
    book_5_1: THREE.Mesh
    book_5_2: THREE.Mesh
    book_6_1: THREE.Mesh
    book_6_2: THREE.Mesh
    book_7_1: THREE.Mesh
    book_7_2: THREE.Mesh
    book_8_1: THREE.Mesh
    book_8_2: THREE.Mesh
    open_book_1: THREE.Mesh
    open_book_2: THREE.Mesh
    pencil_holder: THREE.Mesh
    pencil_1: THREE.Mesh
    pencil_2: THREE.Mesh
    pencil_3: THREE.Mesh
    pot_1: THREE.Mesh
    pot_2: THREE.Mesh
    cactus001: THREE.Mesh
    pot_1_1: THREE.Mesh
    pot_1_2: THREE.Mesh
    cactus_1: THREE.Mesh
    flower: THREE.Mesh
    cactus_2: THREE.Mesh
    flower_1: THREE.Mesh
    flower_2: THREE.Mesh
    flower_bud: THREE.Mesh
    cactus_3: THREE.Mesh
    cactus_4: THREE.Mesh
    cactus_5: THREE.Mesh
    dioscorea: THREE.Mesh
    dioscorea_leaf: THREE.Mesh
    dioscorea_root: THREE.Mesh
    dioscorea_stem: THREE.Mesh
    dioscorea_stem_1: THREE.Mesh
    dioscorea_stem_2: THREE.Mesh
    pandurata_pot: THREE.Mesh
    pandurata_pot_1: THREE.Mesh
    pandurata_leaf: THREE.Mesh
    pandurata_leaf_10: THREE.Mesh
    pandurata_leaf_11: THREE.Mesh
    pandurata_leaf_12: THREE.Mesh
    pandurata_leaf_13: THREE.Mesh
    pandurata_leaf_14: THREE.Mesh
    pandurata_leaf_15: THREE.Mesh
    pandurata_leaf_16: THREE.Mesh
    pandurata_leaf_17: THREE.Mesh
    pandurata_leaf_18: THREE.Mesh
    pandurata_leaf_19: THREE.Mesh
    pandurata_leaf_2: THREE.Mesh
    pandurata_leaf_20: THREE.Mesh
    pandurata_leaf_21: THREE.Mesh
    pandurata_leaf_22: THREE.Mesh
    pandurata_leaf_23: THREE.Mesh
    pandurata_leaf_24: THREE.Mesh
    pandurata_leaf_25: THREE.Mesh
    pandurata_leaf_26: THREE.Mesh
    pandurata_leaf_27: THREE.Mesh
    pandurata_leaf_28: THREE.Mesh
    pandurata_leaf_29: THREE.Mesh
    pandurata_leaf_3: THREE.Mesh
    pandurata_leaf_30: THREE.Mesh
    pandurata_leaf_31: THREE.Mesh
    pandurata_leaf_32: THREE.Mesh
    pandurata_leaf_33: THREE.Mesh
    pandurata_leaf_34: THREE.Mesh
    pandurata_leaf_35: THREE.Mesh
    pandurata_leaf_36: THREE.Mesh
    pandurata_leaf_37: THREE.Mesh
    pandurata_leaf_38: THREE.Mesh
    pandurata_leaf_4: THREE.Mesh
    pandurata_leaf_5: THREE.Mesh
    pandurata_leaf_6: THREE.Mesh
    pandurata_leaf_7: THREE.Mesh
    pandurata_leaf_8: THREE.Mesh
    pandurata_leaf_9: THREE.Mesh
    pandurata_stem: THREE.Mesh
    clock_1: THREE.Mesh
    clock_3: THREE.Mesh
    clock_center: THREE.Mesh
    clock_hour: THREE.Mesh
    clock_minute: THREE.Mesh
    clock_tag: THREE.Mesh
    clock_tag_2: THREE.Mesh
    pilea_1: THREE.Mesh
    pilea_2: THREE.Mesh
    pilea_leaf: THREE.Mesh
    pilea_leaf_1_1: THREE.Mesh
    pilea_leaf_10: THREE.Mesh
    pilea_leaf_11: THREE.Mesh
    pilea_leaf_12: THREE.Mesh
    pilea_leaf_13: THREE.Mesh
    pilea_leaf_14: THREE.Mesh
    pilea_leaf_15: THREE.Mesh
    pilea_leaf_16: THREE.Mesh
    pilea_leaf_17: THREE.Mesh
    pilea_leaf_2: THREE.Mesh
    pilea_leaf_3: THREE.Mesh
    pilea_leaf_4: THREE.Mesh
    pilea_leaf_5: THREE.Mesh
    pilea_leaf_6: THREE.Mesh
    pilea_leaf_7: THREE.Mesh
    pilea_leaf_8: THREE.Mesh
    pilea_leaf_9: THREE.Mesh
    pilea_stem: THREE.Mesh
    hoya_1: THREE.Mesh
    hoya_2: THREE.Mesh
    hoya_leaf: THREE.Mesh
    react: THREE.Mesh
    react_1_1: THREE.Mesh
    react_2: THREE.Mesh
    react_3: THREE.Mesh
    clock_2_1: THREE.Mesh
    clock_2_2: THREE.Mesh
    clock_center_2: THREE.Mesh
    clock_hour_2: THREE.Mesh
    clock_minute_2: THREE.Mesh
    lego: THREE.Mesh
    lego_1_1: THREE.Mesh
    lego_100: THREE.Mesh
    lego_101: THREE.Mesh
    lego_102: THREE.Mesh
    lego_103: THREE.Mesh
    lego_104: THREE.Mesh
    lego_105: THREE.Mesh
    lego_106: THREE.Mesh
    lego_107: THREE.Mesh
    lego_108: THREE.Mesh
    lego_109: THREE.Mesh
    lego_11: THREE.Mesh
    lego_10: THREE.Mesh
    lego_10001: THREE.Mesh
    lego_110: THREE.Mesh
    lego_111: THREE.Mesh
    lego_112: THREE.Mesh
    lego_113: THREE.Mesh
    lego_114: THREE.Mesh
    lego_115: THREE.Mesh
    lego_117: THREE.Mesh
    lego_118: THREE.Mesh
    lego_119: THREE.Mesh
    lego_12: THREE.Mesh
    lego_120: THREE.Mesh
    lego_121: THREE.Mesh
    lego_122: THREE.Mesh
    lego_123: THREE.Mesh
    lego_124: THREE.Mesh
    lego_125: THREE.Mesh
    lego_126: THREE.Mesh
    lego_13: THREE.Mesh
    lego_116: THREE.Mesh
    lego_14: THREE.Mesh
    lego_15: THREE.Mesh
    lego_16: THREE.Mesh
    lego_17: THREE.Mesh
    lego_18: THREE.Mesh
    lego_19: THREE.Mesh
    lego_2: THREE.Mesh
    lego_20: THREE.Mesh
    lego_21: THREE.Mesh
    lego_22: THREE.Mesh
    lego_23: THREE.Mesh
    lego_24: THREE.Mesh
    lego_25: THREE.Mesh
    lego_26: THREE.Mesh
    lego_27: THREE.Mesh
    lego_28: THREE.Mesh
    lego_29: THREE.Mesh
    lego_3: THREE.Mesh
    lego_30: THREE.Mesh
    lego_31: THREE.Mesh
    lego_32: THREE.Mesh
    lego_33: THREE.Mesh
    lego_34: THREE.Mesh
    lego_35: THREE.Mesh
    lego_36: THREE.Mesh
    lego_37: THREE.Mesh
    lego_38: THREE.Mesh
    lego_39: THREE.Mesh
    lego_4: THREE.Mesh
    lego_40: THREE.Mesh
    lego_41: THREE.Mesh
    lego_42: THREE.Mesh
    lego_43: THREE.Mesh
    lego_44: THREE.Mesh
    lego_45: THREE.Mesh
    lego_46: THREE.Mesh
    lego_47: THREE.Mesh
    lego_48: THREE.Mesh
    lego_49: THREE.Mesh
    lego_5: THREE.Mesh
    lego_50: THREE.Mesh
    lego_51: THREE.Mesh
    lego_52: THREE.Mesh
    lego_53: THREE.Mesh
    lego_54: THREE.Mesh
    lego_55: THREE.Mesh
    lego_56: THREE.Mesh
    lego_57: THREE.Mesh
    lego_58: THREE.Mesh
    lego_59: THREE.Mesh
    lego_6: THREE.Mesh
    lego_60: THREE.Mesh
    lego_61: THREE.Mesh
    lego_62: THREE.Mesh
    lego_63: THREE.Mesh
    lego_64: THREE.Mesh
    lego_65: THREE.Mesh
    lego_66: THREE.Mesh
    lego_67: THREE.Mesh
    lego_68: THREE.Mesh
    lego_69: THREE.Mesh
    lego_7: THREE.Mesh
    lego_70: THREE.Mesh
    lego_71: THREE.Mesh
    lego_72: THREE.Mesh
    lego_73: THREE.Mesh
    lego_74: THREE.Mesh
    lego_75: THREE.Mesh
    lego_76: THREE.Mesh
    lego_77: THREE.Mesh
    lego_78: THREE.Mesh
    lego_79: THREE.Mesh
    lego_8: THREE.Mesh
    lego_80: THREE.Mesh
    lego_81: THREE.Mesh
    lego_82: THREE.Mesh
    lego_83: THREE.Mesh
    lego_84: THREE.Mesh
    lego_85: THREE.Mesh
    lego_86: THREE.Mesh
    lego_87: THREE.Mesh
    lego_88: THREE.Mesh
    lego_89: THREE.Mesh
    lego_9: THREE.Mesh
    lego_90: THREE.Mesh
    lego_91: THREE.Mesh
    lego_92: THREE.Mesh
    lego_93: THREE.Mesh
    lego_94: THREE.Mesh
    lego_95: THREE.Mesh
    lego_96: THREE.Mesh
    lego_97: THREE.Mesh
    lego_98: THREE.Mesh
    lego_99: THREE.Mesh
  }
  materials: {
    walls: THREE.MeshStandardMaterial
    dark_wood: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    copper: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
    blue: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    orange: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    light_metal: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    dark_leaf: THREE.MeshStandardMaterial
    leaf: THREE.MeshStandardMaterial
    terracota: THREE.MeshStandardMaterial
    medium_leaf: THREE.MeshStandardMaterial
    emission: THREE.MeshStandardMaterial
  }
}

export function Room (props: JSX.IntrinsicElements['group']): ReactElement {
  const { nodes, materials } = useGLTF('/models/room.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.walls.geometry} material={materials.walls} />
      <mesh geometry={nodes.floor.geometry} material={materials.dark_wood} />
      <mesh geometry={nodes.flooring.geometry} material={materials.wood} />
      <mesh geometry={nodes.desk.geometry} material={materials.dark_wood}>
        <mesh geometry={nodes.desk_leg.geometry} material={materials.copper} position={[-1.43, 0.72, 1.58]} scale={[0.96, 1, 1]} />
        <group position={[-1.95, -1.08, 0.56]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.desk_shelfs_1.geometry} material={materials.white} />
          <mesh geometry={nodes.desk_shelfs_2.geometry} material={materials.copper} />
        </group>
      </mesh>
      <mesh geometry={nodes.shelf_1.geometry} material={materials.wood} position={[-1.75, 2.54, 0.74]} scale={[1.52, 1, 1.53]} />
      <mesh geometry={nodes.chair.geometry} material={materials.white} position={[-0.54, 0.05, 0.82]} rotation={[0, 0.71, 0]}>
        <mesh geometry={nodes.chair_leg.geometry} material={materials.copper} />
        <mesh geometry={nodes.chair_pillow.geometry} material={materials.blue} />
        <mesh geometry={nodes.chair_support.geometry} material={materials.copper} />
        <mesh geometry={nodes.chair_wheel.geometry} material={materials.white} />
        <mesh geometry={nodes.chair_wheel_protector.geometry} material={materials.copper} />
      </mesh>
      <mesh geometry={nodes.bookshelf.geometry} material={materials.dark_wood} position={[0.69, 0.72, -1.53]} scale={[1, 1, 1.25]} />
      <mesh geometry={nodes.window.geometry} material={materials.dark_wood} position={[0, -0.03, 0]}>
        <mesh geometry={nodes.window_glass.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.window_glass_trim.geometry} material={materials.copper} />
      </mesh>
      <mesh geometry={nodes.curtain.geometry} material={materials.wood} position={[0.67, 3.01, -1.83]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.curtain_1.geometry} material={materials.orange} position={[0.84, 0.74, -0.15]} rotation={[Math.PI / 2, 1.57, 0]} scale={[1, 0.92, 1]} />
        <mesh geometry={nodes.curtain_2.geometry} material={materials.orange} position={[0.84, -0.77, -0.15]} rotation={[Math.PI / 2, 1.57, 0]} scale={[1, 0.92, 1]} />
        <mesh geometry={nodes.curtain_holder_1.geometry} material={materials.copper} position={[-0.02, 1.15, -0.17]} rotation={[Math.PI / 2, 1.57, 0]} />
        <mesh geometry={nodes.curtain_holder_2.geometry} material={materials.copper} position={[-0.02, -1.14, -0.17]} rotation={[Math.PI / 2, 1.57, 0]} />
      </mesh>
      <group position={[-1.56, 1.62, 0.87]}>
        <mesh geometry={nodes.computer_1.geometry} material={materials.white} />
        <mesh geometry={nodes.computer_2.geometry} material={materials.black} />
        <mesh geometry={nodes.computer_3.geometry} material={materials.light_metal} />
        <mesh geometry={nodes.keyboard.geometry} material={materials.white} position={[1.56, -1.62, -0.87]} />
        <mesh geometry={nodes.mouse.geometry} material={materials.white} position={[0.31, -0.26, -0.46]} rotation={[0, 0.2, 0]} scale={0.95}>
          <mesh geometry={nodes.mouse_scroll.geometry} material={materials.black} position={[1.25, -1.35, -0.32]} />
        </mesh>
      </group>
      <mesh geometry={nodes.notebook.geometry} material={materials.metal}>
        <mesh geometry={nodes.notebook_hinge.geometry} material={materials.metal} position={[-1.32, 1.36, -0.17]} rotation={[Math.PI, -1.12, Math.PI]} scale={0.72} />
        <mesh geometry={nodes.notebook_keyboard.geometry} material={materials.metal} position={[-1.22, 1.37, -0.13]} rotation={[Math.PI, -1.12, Math.PI]} scale={0.72} />
        <group position={[-1.36, 1.49, -0.19]} rotation={[Math.PI, -1.12, Math.PI]} scale={0.72}>
          <mesh geometry={nodes.notebook_screen_1.geometry} material={materials.metal} />
          <mesh geometry={nodes.notebook_screen_2.geometry} material={materials.black} />
        </group>
        <mesh geometry={nodes.notebook_trackpad.geometry} material={materials.light_metal} position={[-1.1, 1.36, -0.07]} rotation={[Math.PI, -1.12, Math.PI]} scale={0.72} />
      </mesh>
      <group position={[-1.34, 1.41, 1.4]} rotation={[-Math.PI, 1.03, -Math.PI]} scale={1.11}>
        <mesh geometry={nodes.mate_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.mate_2.geometry} material={materials.dark_leaf} />
        <mesh geometry={nodes.straw.geometry} material={materials.metal} position={[-1.14, -1.39, -1.26]} />
      </group>
      <mesh geometry={nodes.thermos.geometry} material={materials.metal} position={[-0.25, 0, -0.08]} />
      <mesh geometry={nodes.coaster.geometry} material={materials.blue} position={[-1.34, 1.33, 1.4]} scale={0.08} />
      <mesh geometry={nodes.rug.geometry} material={materials.orange} position={[-0.84, 0.27, 0.99]} scale={[0.91, 0.38, 0.91]} />
      <group position={[-0.19, 0.93, -1.4]} scale={[0.75, 0.74, 0.75]}>
        <mesh geometry={nodes.book_1.geometry} material={materials.white} />
        <mesh geometry={nodes.book_2.geometry} material={materials.blue} />
        <group position={[1.36, -0.6, 0]}>
          <mesh geometry={nodes.book_1_2.geometry} material={materials.white} />
          <mesh geometry={nodes.book_1_3.geometry} material={materials.dark_leaf} />
        </group>
        <group position={[1.1, -0.77, -0.03]} rotation={[0, 0, -Math.PI / 2]} scale={[1.02, 0.98, 1]}>
          <mesh geometry={nodes.book_2_2.geometry} material={materials.white} />
          <mesh geometry={nodes.book_2_3.geometry} material={materials.orange} />
        </group>
        <group position={[0.97, 0.01, 0.03]} rotation={[0, 0, -0.29]}>
          <mesh geometry={nodes.book_3_1.geometry} material={materials.white} />
          <mesh geometry={nodes.book_3_2.geometry} material={materials.orange} />
        </group>
        <group position={[1.31, 0.07, -0.15]} rotation={[Math.PI, 0.2, -Math.PI / 2]} scale={[1.02, 0.98, 1]}>
          <mesh geometry={nodes.book_4_1.geometry} material={materials.white} />
          <mesh geometry={nodes.book_4_2.geometry} material={materials.leaf} />
        </group>
        <group position={[1.26, -0.15, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1.02, 0.98, 1]}>
          <mesh geometry={nodes.book_5_1.geometry} material={materials.white} />
          <mesh geometry={nodes.book_5_2.geometry} material={materials.dark_leaf} />
        </group>
        <group position={[1.87, -0.6, -0.1]} rotation={[-Math.PI, 0, 0.29]}>
          <mesh geometry={nodes.book_6_1.geometry} material={materials.white} />
          <mesh geometry={nodes.book_6_2.geometry} material={materials.blue} />
        </group>
        <group position={[1.98, -0.6, -0.02]} rotation={[0, 0, -0.29]}>
          <mesh geometry={nodes.book_7_1.geometry} material={materials.white} />
          <mesh geometry={nodes.book_7_2.geometry} material={materials.leaf} />
        </group>
        <group position={[2.15, -0.6, 0.02]}>
          <mesh geometry={nodes.book_8_1.geometry} material={materials.white} />
          <mesh geometry={nodes.book_8_2.geometry} material={materials.leaf} />
        </group>
      </group>
      <group position={[0.85, 1.19, -1.6]}>
        <mesh geometry={nodes.open_book_1.geometry} material={materials.blue} />
        <mesh geometry={nodes.open_book_2.geometry} material={materials.white} />
      </group>
      <mesh geometry={nodes.pencil_holder.geometry} material={materials.orange} position={[0.54, 1.21, -1.64]} rotation={[0, 1.29, 0]}>
        <mesh geometry={nodes.pencil_1.geometry} material={materials.wood} position={[-0.54, -1.42, 1.99]} scale={1.17} />
        <mesh geometry={nodes.pencil_2.geometry} material={materials.wood} position={[-0.54, -1.42, 1.99]} scale={1.17} />
        <mesh geometry={nodes.pencil_3.geometry} material={materials.wood} position={[-0.54, -1.42, 1.99]} scale={1.17} />
      </mesh>
      <group position={[-1.72, 2.66, 0.5]} scale={1.48}>
        <mesh geometry={nodes.pot_1.geometry} material={materials.terracota} />
        <mesh geometry={nodes.pot_2.geometry} material={materials.dark_wood} />
        <mesh geometry={nodes.cactus001.geometry} material={materials.medium_leaf} position={[0.03, -1.24, 1.56]} />
      </group>
      <group position={[-0.05, 1.21, -1.53]} scale={[2.96, 1.29, 2.96]}>
        <mesh geometry={nodes.pot_1_1.geometry} material={materials.terracota} />
        <mesh geometry={nodes.pot_1_2.geometry} material={materials.dark_wood} />
        <mesh geometry={nodes.cactus_1.geometry} material={materials.leaf} position={[0.01, 0.04, -0.02]} scale={[0.74, 0.48, 0.74]}>
          <mesh geometry={nodes.flower.geometry} material={materials.orange} position={[0, 0.11, 0]} scale={[0.06, 0.21, 0.06]} />
        </mesh>
        <mesh geometry={nodes.cactus_2.geometry} material={materials.leaf} position={[0.02, 0.03, 0.01]} scale={[0.46, 0.3, 0.46]}>
          <mesh geometry={nodes.flower_1.geometry} material={materials.orange} position={[0, 0.11, 0]} rotation={[0.36, 0, 0]} scale={[0.09, 0.32, 0.12]} />
          <mesh geometry={nodes.flower_2.geometry} material={materials.orange} position={[0, 0.11, 0]} rotation={[1.06, -1.13, 1.69]} scale={[0.11, 0.3, 0.06]} />
          <mesh geometry={nodes.flower_bud.geometry} material={materials.orange} position={[0.01, 0.12, 0]} rotation={[-Math.PI, 0, 0.55]} scale={[0.46, 1.04, 0.26]} />
        </mesh>
        <mesh geometry={nodes.cactus_3.geometry} material={materials.medium_leaf} position={[-0.02, 0.05, 0.01]} scale={[0.24, 0.7, 0.24]} />
        <mesh geometry={nodes.cactus_4.geometry} material={materials.medium_leaf} position={[-0.03, 0.05, -0.02]} scale={[0.42, 1.2, 0.42]} />
        <mesh geometry={nodes.cactus_5.geometry} material={materials.leaf} position={[-0.03, 0.03, 0.03]} scale={[0.33, 0.22, 0.33]} />
      </group>
      <mesh geometry={nodes.dioscorea.geometry} material={materials.copper} position={[-1.76, 2.72, 0.84]} scale={[2.11, 1.25, 2.11]}>
        <mesh geometry={nodes.dioscorea_leaf.geometry} material={materials.leaf} position={[0.03, 0.14, 0]} rotation={[0, 0, -0.66]} scale={[0.62, 0.69, 0.47]} />
        <mesh geometry={nodes.dioscorea_root.geometry} material={materials.wood} position={[0, 0.08, 0]} rotation={[0, 0, 1.83]} scale={[0.54, 0.62, 0.42]} />
        <mesh geometry={nodes.dioscorea_stem.geometry} material={materials.leaf} position={[0.89, -2.17, -0.64]} scale={[0.47, 0.8, 0.47]} />
        <mesh geometry={nodes.dioscorea_stem_1.geometry} material={materials.leaf} position={[0.09, 0.08, 0.03]} rotation={[0, -0.49, 0]} scale={[0.47, 0.8, 0.47]} />
        <mesh geometry={nodes.dioscorea_stem_2.geometry} material={materials.leaf} position={[0.06, 0.1, -0.08]} rotation={[0, 0.87, 0]} scale={[0.47, 0.8, 0.47]} />
      </mesh>
      <group position={[-1.39, 0.54, -1.26]} rotation={[0, 0.45, 0]} scale={1.24}>
        <mesh geometry={nodes.pandurata_pot.geometry} material={materials.terracota} />
        <mesh geometry={nodes.pandurata_pot_1.geometry} material={materials.dark_wood} />
        <mesh geometry={nodes.pandurata_leaf.geometry} material={materials.dark_leaf} position={[-1.63, -0.51, -1.56]}>
          <mesh geometry={nodes.pandurata_leaf_10.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_11.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_12.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_13.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_14.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_15.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_16.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_17.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_18.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_19.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_2.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_20.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_21.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_22.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_23.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_24.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_25.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_26.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_27.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_28.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_29.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_3.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_30.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_31.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_32.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_33.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_34.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_35.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_36.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_37.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_38.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_4.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_5.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_6.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_7.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_8.geometry} material={materials.dark_leaf} />
          <mesh geometry={nodes.pandurata_leaf_9.geometry} material={materials.dark_leaf} />
        </mesh>
        <mesh geometry={nodes.pandurata_stem.geometry} material={materials.dark_wood} position={[-1.63, -0.51, -1.56]} />
      </group>
      <group position={[-1.96, 2.96, -1.41]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.clock_1.geometry} material={materials.copper} />
        <mesh geometry={nodes.clock_3.geometry} material={materials.white} />
        <mesh geometry={nodes.clock_center.geometry} material={materials.copper} position={[-1.56, -0.34, -1.4]} />
        <mesh geometry={nodes.clock_hour.geometry} material={materials.copper} position={[-1.56, -0.34, -1.4]} />
        <mesh geometry={nodes.clock_minute.geometry} material={materials.copper} position={[-1.56, -0.34, -1.4]} />
      </group>
      <mesh geometry={nodes.clock_tag.geometry} material={materials.wood} position={[-1.96, 3.38, -1.42]} rotation={[0, 1.57, 0]} />
      <mesh geometry={nodes.clock_tag_2.geometry} material={materials.wood} position={[-1.96, 3.38, -0.65]} rotation={[0, 1.57, 0]} />
      <group position={[-1.77, 2.72, 0.01]} scale={1.24}>
        <mesh geometry={nodes.pilea_1.geometry} material={materials.terracota} />
        <mesh geometry={nodes.pilea_2.geometry} material={materials.dark_wood} />
        <mesh geometry={nodes.pilea_leaf.geometry} material={materials.leaf} position={[0, 0.12, 0]} rotation={[1.7, 0.24, -0.02]} scale={0.3}>
          <mesh geometry={nodes.pilea_leaf_1_1.geometry} material={materials.leaf} position={[-0.02, 0.01, 0.08]} rotation={[0, 0, 1.07]} scale={0.95} />
          <mesh geometry={nodes.pilea_leaf_10.geometry} material={materials.leaf} position={[0.03, -0.02, -0.12]} rotation={[0.16, -0.06, 0.57]} scale={0.99} />
          <mesh geometry={nodes.pilea_leaf_11.geometry} material={materials.leaf} position={[0.03, -0.02, -0.14]} rotation={[-0.26, -0.11, 1.6]} scale={0.68} />
          <mesh geometry={nodes.pilea_leaf_12.geometry} material={materials.leaf} position={[0.02, -0.01, -0.1]} rotation={[-0.41, -0.04, 2.36]} scale={0.85} />
          <mesh geometry={nodes.pilea_leaf_13.geometry} material={materials.leaf} position={[0.06, -0.03, -0.25]} rotation={[0.01, -1, -2.26]} scale={0.78} />
          <mesh geometry={nodes.pilea_leaf_14.geometry} material={materials.leaf} position={[0.08, -0.04, -0.33]} rotation={[-0.37, -0.23, -1.48]} scale={0.91} />
          <mesh geometry={nodes.pilea_leaf_15.geometry} material={materials.leaf} position={[0.06, -0.03, -0.25]} rotation={[-0.13, -0.24, -0.89]} scale={0.91} />
          <mesh geometry={nodes.pilea_leaf_16.geometry} material={materials.leaf} position={[0.06, -0.03, -0.25]} rotation={[-0.12, -0.92, -1.96]} scale={0.52} />
          <mesh geometry={nodes.pilea_leaf_17.geometry} material={materials.leaf} position={[0.08, -0.04, -0.31]} rotation={[-0.82, -0.5, 2.98]} scale={0.5} />
          <mesh geometry={nodes.pilea_leaf_2.geometry} material={materials.leaf} rotation={[-0.13, -0.24, 1.91]} scale={0.91} />
          <mesh geometry={nodes.pilea_leaf_3.geometry} material={materials.leaf} position={[-0.02, 0.01, 0.08]} rotation={[-0.13, -0.24, 2.98]} scale={1.02} />
          <mesh geometry={nodes.pilea_leaf_4.geometry} material={materials.leaf} rotation={[-0.33, -0.24, -2.53]} />
          <mesh geometry={nodes.pilea_leaf_5.geometry} material={materials.leaf} position={[-0.02, 0.01, 0.08]} rotation={[-0.13, -0.24, -1.43]} scale={0.91} />
          <mesh geometry={nodes.pilea_leaf_6.geometry} material={materials.leaf} rotation={[-0.13, -0.24, -0.58]} scale={0.78} />
          <mesh geometry={nodes.pilea_leaf_7.geometry} material={materials.leaf} position={[-0.02, 0.01, 0.08]} rotation={[-0.13, -0.24, 0.49]} scale={0.91} />
          <mesh geometry={nodes.pilea_leaf_8.geometry} material={materials.leaf} position={[0.06, -0.03, -0.25]} rotation={[0.14, 0.39, 0.73]} scale={0.45} />
          <mesh geometry={nodes.pilea_leaf_9.geometry} material={materials.leaf} position={[0.06, -0.03, -0.25]} rotation={[0.14, -0.31, -0.25]} />
        </mesh>
        <mesh geometry={nodes.pilea_stem.geometry} material={materials.leaf} position={[0, 0.16, 0]} scale={[0, 0.07, 0]} />
      </group>
      <group position={[-1.61, 2.68, 0.26]} scale={0.61}>
        <mesh geometry={nodes.hoya_1.geometry} material={materials.terracota} />
        <mesh geometry={nodes.hoya_2.geometry} material={materials.dark_wood} />
        <mesh geometry={nodes.hoya_leaf.geometry} material={materials.dark_leaf} position={[0, 0.09, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.06, 0.06, 0.05]} />
      </group>
      <mesh geometry={nodes.react.geometry} material={materials.emission} position={[-1.26, 2.5, -1.96]}>
        <mesh geometry={nodes.react_1_1.geometry} material={materials.emission} position={[1.37, -3.07, 1.96]} />
        <mesh geometry={nodes.react_2.geometry} material={materials.emission} position={[1.37, -3.07, 1.96]} />
        <mesh geometry={nodes.react_3.geometry} material={materials.emission} position={[1.37, -3.07, 1.96]} />
      </mesh>
      <group position={[-1.96, 2.96, -0.66]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.clock_2_1.geometry} material={materials.copper} />
        <mesh geometry={nodes.clock_2_2.geometry} material={materials.white} />
        <mesh geometry={nodes.clock_center_2.geometry} material={materials.copper} position={[-1.56, -0.34, -1.4]} />
        <mesh geometry={nodes.clock_hour_2.geometry} material={materials.copper} position={[-1.56, -0.34, -1.4]} />
        <mesh geometry={nodes.clock_minute_2.geometry} material={materials.copper} position={[-1.56, -0.34, -1.4]} />
      </group>
      <mesh geometry={nodes.lego.geometry} material={materials.blue} position={[-1.69, 2.63, 1.44]}>
        <mesh geometry={nodes.lego_1_1.geometry} material={materials.orange} position={[-0.19, -0.03, 0.19]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_100.geometry} material={materials.medium_leaf} position={[-0.13, 0.2, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_101.geometry} material={materials.medium_leaf} position={[-0.05, 0.2, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_102.geometry} material={materials.medium_leaf} position={[0.02, 0.22, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_103.geometry} material={materials.blue} position={[-0.19, 0.25, 0.15]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_104.geometry} material={materials.blue} position={[-0.19, 0.23, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_105.geometry} material={materials.medium_leaf} position={[-0.19, 0.23, -0.08]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_106.geometry} material={materials.medium_leaf} position={[-0.19, 0.23, -0.16]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_107.geometry} material={materials.medium_leaf} position={[-0.09, 0.23, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_108.geometry} material={materials.blue} position={[-0.02, 0.25, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_109.geometry} material={materials.medium_leaf} position={[-0.17, 0.23, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_11.geometry} material={materials.medium_leaf} position={[0.08, -0.02, -0.12]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_10.geometry} material={materials.medium_leaf} position={[-0.19, 0.23, 0.07]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_10001.geometry} material={materials.medium_leaf} position={[-0.19, 0, 0.15]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_110.geometry} material={materials.medium_leaf} position={[-0.19, 0.28, 0.11]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_111.geometry} material={materials.medium_leaf} position={[-0.19, 0.26, 0.03]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_112.geometry} material={materials.medium_leaf} position={[-0.19, 0.26, -0.04]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_113.geometry} material={materials.medium_leaf} position={[-0.19, 0.26, -0.12]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_114.geometry} material={materials.medium_leaf} position={[-0.19, 0.26, -0.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_115.geometry} material={materials.medium_leaf} position={[-0.13, 0.26, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_117.geometry} material={materials.blue} position={[-0.05, 0.28, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_118.geometry} material={materials.medium_leaf} position={[-0.19, 0.29, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_119.geometry} material={materials.medium_leaf} position={[-0.19, 0.29, -0.08]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_12.geometry} material={materials.medium_leaf} position={[0.08, -0.03, -0.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_120.geometry} material={materials.medium_leaf} position={[-0.19, 0.3, -0.16]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_121.geometry} material={materials.medium_leaf} position={[-0.09, 0.31, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_122.geometry} material={materials.medium_leaf} position={[-0.17, 0.31, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_123.geometry} material={materials.medium_leaf} position={[-0.19, 0.33, 0.03]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_124.geometry} material={materials.orange} position={[-0.19, 0.32, -0.04]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_125.geometry} material={materials.medium_leaf} position={[-0.19, 0.33, -0.12]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_126.geometry} material={materials.orange} position={[-0.19, 0.36, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_13.geometry} material={materials.medium_leaf} position={[-0.13, -0.03, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_116.geometry} material={materials.medium_leaf} position={[-0.19, 0.3, 0.07]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_14.geometry} material={materials.medium_leaf} position={[-0.05, -0.03, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_15.geometry} material={materials.blue} position={[0.02, -0.03, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_16.geometry} material={materials.medium_leaf} position={[-0.13, -0.03, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_17.geometry} material={materials.medium_leaf} position={[-0.05, -0.03, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_18.geometry} material={materials.orange} position={[0.02, -0.03, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_19.geometry} material={materials.blue} position={[-0.19, 0, 0.07]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_2.geometry} material={materials.blue} position={[-0.19, -0.03, 0.11]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_20.geometry} material={materials.medium_leaf} position={[-0.19, 0, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_21.geometry} material={materials.medium_leaf} position={[-0.19, 0, -0.08]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_22.geometry} material={materials.medium_leaf} position={[-0.19, 0, -0.16]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_23.geometry} material={materials.blue} position={[0.08, 0.01, 0.15]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_24.geometry} material={materials.medium_leaf} position={[0.08, 0.01, 0.07]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_25.geometry} material={materials.medium_leaf} position={[-0.04, 0, 0.08]} rotation={[-Math.PI, 0.58, -Math.PI]} />
        <mesh geometry={nodes.lego_26.geometry} material={materials.medium_leaf} rotation={[Math.PI, -1.29, Math.PI]} />
        <mesh geometry={nodes.lego_27.geometry} material={materials.medium_leaf} position={[0.08, 0.01, -0.16]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_28.geometry} material={materials.medium_leaf} position={[-0.09, 0.01, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_29.geometry} material={materials.medium_leaf} position={[-0.02, 0.01, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_3.geometry} material={materials.medium_leaf} position={[-0.19, -0.03, 0.03]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_30.geometry} material={materials.blue} position={[0.06, 0.01, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_31.geometry} material={materials.medium_leaf} position={[-0.17, 0, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_32.geometry} material={materials.orange} position={[-0.09, 0, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_33.geometry} material={materials.orange} position={[-0.02, 0, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_34.geometry} material={materials.orange} position={[0.06, 0, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_35.geometry} material={materials.medium_leaf} position={[-0.17, 0, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_36.geometry} material={materials.medium_leaf} position={[-0.19, 0.03, 0.19]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_37.geometry} material={materials.medium_leaf} position={[-0.19, 0.03, 0.11]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_38.geometry} material={materials.medium_leaf} position={[-0.19, 0.03, 0.03]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_39.geometry} material={materials.medium_leaf} position={[-0.19, 0.03, -0.04]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_4.geometry} material={materials.medium_leaf} position={[-0.19, -0.03, -0.04]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_40.geometry} material={materials.medium_leaf} position={[-0.19, 0.03, -0.12]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_41.geometry} material={materials.medium_leaf} position={[-0.19, 0.03, -0.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_42.geometry} material={materials.medium_leaf} position={[0.08, 0.04, -0.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_43.geometry} material={materials.medium_leaf} position={[-0.13, 0.04, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_44.geometry} material={materials.medium_leaf} position={[-0.13, 0.03, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_45.geometry} material={materials.orange} position={[-0.05, 0.03, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_46.geometry} material={materials.medium_leaf} position={[0.02, 0.03, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_47.geometry} material={materials.medium_leaf} position={[-0.19, 0.06, 0.15]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_48.geometry} material={materials.medium_leaf} position={[-0.19, 0.06, 0.07]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_49.geometry} material={materials.blue} position={[-0.19, 0.06, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_5.geometry} material={materials.medium_leaf} position={[-0.19, -0.03, -0.12]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_50.geometry} material={materials.medium_leaf} position={[-0.19, 0.06, -0.08]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_51.geometry} material={materials.medium_leaf} position={[-0.19, 0.06, -0.16]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_52.geometry} material={materials.orange} position={[-0.17, 0.06, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_53.geometry} material={materials.medium_leaf} position={[-0.09, 0.06, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_54.geometry} material={materials.medium_leaf} position={[-0.02, 0.06, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_55.geometry} material={materials.medium_leaf} position={[0.06, 0.06, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_56.geometry} material={materials.medium_leaf} position={[-0.17, 0.06, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_57.geometry} material={materials.medium_leaf} position={[-0.19, 0.09, 0.19]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_58.geometry} material={materials.medium_leaf} position={[-0.19, 0.09, 0.11]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_59.geometry} material={materials.blue} position={[-0.19, 0.1, 0.03]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_6.geometry} material={materials.medium_leaf} position={[-0.19, -0.03, -0.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_60.geometry} material={materials.blue} position={[-0.19, 0.1, -0.04]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_61.geometry} material={materials.blue} position={[-0.19, 0.09, -0.12]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_62.geometry} material={materials.medium_leaf} position={[-0.19, 0.09, -0.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_63.geometry} material={materials.medium_leaf} position={[0.08, 0.1, -0.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_64.geometry} material={materials.orange} position={[-0.13, 0.1, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_65.geometry} material={materials.medium_leaf} position={[-0.13, 0.09, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_66.geometry} material={materials.medium_leaf} position={[-0.05, 0.1, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_67.geometry} material={materials.blue} position={[0.02, 0.1, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_68.geometry} material={materials.medium_leaf} position={[-0.19, 0.11, 0.15]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_69.geometry} material={materials.blue} position={[-0.19, 0.13, 0.07]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_7.geometry} material={materials.blue} position={[0.08, -0.03, 0.19]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_70.geometry} material={materials.medium_leaf} position={[-0.04, 0, 0.08]} rotation={[-Math.PI, 0.58, -Math.PI]} />
        <mesh geometry={nodes.lego_71.geometry} material={materials.orange} position={[-0.19, 0.13, -0.08]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_72.geometry} material={materials.medium_leaf} position={[-0.19, 0.11, -0.16]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_73.geometry} material={materials.orange} position={[-0.17, 0.13, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_74.geometry} material={materials.medium_leaf} position={[-0.09, 0.13, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_75.geometry} material={materials.medium_leaf} position={[0.01, 0.03, -0.04]} rotation={[Math.PI, -1.29, Math.PI]} />
        <mesh geometry={nodes.lego_76.geometry} material={materials.medium_leaf} position={[0.06, 0.13, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_77.geometry} material={materials.medium_leaf} position={[-0.17, 0.11, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_78.geometry} material={materials.medium_leaf} position={[-0.19, 0.14, 0.19]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_79.geometry} material={materials.medium_leaf} position={[-0.19, 0.14, 0.11]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_8.geometry} material={materials.medium_leaf} position={[0.08, -0.03, 0.11]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_80.geometry} material={materials.orange} position={[-0.19, 0.14, -0.12]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_81.geometry} material={materials.medium_leaf} position={[-0.19, 0.14, -0.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_82.geometry} material={materials.medium_leaf} position={[0.08, 0.16, -0.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_83.geometry} material={materials.medium_leaf} position={[-0.13, 0.14, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_84.geometry} material={materials.medium_leaf} position={[-0.19, 0.17, 0.15]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_85.geometry} material={materials.medium_leaf} position={[-0.19, 0.17, 0.07]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_86.geometry} material={materials.medium_leaf} position={[-0.19, 0.17, -0.08]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_87.geometry} material={materials.medium_leaf} position={[-0.19, 0.17, -0.16]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_88.geometry} material={materials.medium_leaf} position={[-0.17, 0.19, 0.21]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_89.geometry} material={materials.medium_leaf} position={[-0.09, 0.17, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_9.geometry} material={materials.orange} position={[0.08, -0.02, 0.03]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_90.geometry} material={materials.medium_leaf} position={[0.06, 0.17, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_91.geometry} material={materials.medium_leaf} position={[-0.17, 0.17, -0.22]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.lego_92.geometry} material={materials.medium_leaf} position={[-0.19, 0.22, 0.19]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_93.geometry} material={materials.medium_leaf} position={[-0.19, 0.2, 0.11]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_94.geometry} material={materials.medium_leaf} position={[-0.19, 0.2, 0.03]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_95.geometry} material={materials.medium_leaf} position={[-0.19, 0.2, -0.04]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_96.geometry} material={materials.medium_leaf} position={[-0.19, 0.2, -0.12]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_97.geometry} material={materials.medium_leaf} position={[-0.19, 0.2, -0.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_98.geometry} material={materials.medium_leaf} position={[0.08, 0.22, -0.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lego_99.geometry} material={materials.medium_leaf} position={[-0.19, 0.36, -0.08]} rotation={[0, 1.57, 0]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/room.glb')
